# app-config.yaml

app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: My Company

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

  proxy:
    '/openfga':
      target: 'http://localhost:8080'
      changeOrigin: true
      allowedMethods: ['GET', 'POST', 'PUT', 'DELETE']
      pathRewrite:
        '^/openfga': ''

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

auth:
  providers:
    guest: {}

scaffolder:
  locations:
    - type: file
      target: ../../examples/entities.yaml

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: ../../examples/entities.yaml

permission:
  enabled: true

# Configuration for the OpenFGA plugin
openfga:
  baseUrl: 'http://localhost:8080'
  storeId: '01JJV73AF055YW4S05828EMJ43'
  authorizationModelId: '01JJV73VNSAZ4DY3JV3Q1ZN720'
